import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f6f7f9' },
  keyboardRoot: { flex: 1 },
  centerScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#f6f7f9',
  },
  mutedText: { color: '#697586', fontSize: 14 },
  accountScreen: {
    flex: 1,
    justifyContent: 'center',
    padding: 18,
    backgroundColor: '#f6f7f9',
  },
  accountEntry: {
    overflow: 'hidden',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d9dee7',
    backgroundColor: '#ffffff',
    shadowColor: '#121926',
    shadowOpacity: 0.12,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 16 },
    elevation: 4,
  },
  accountBrand: {
    minHeight: 212,
    padding: 24,
    justifyContent: 'flex-end',
    gap: 12,
    backgroundColor: '#162330',
  },
  eyebrow: { color: '#697586', fontSize: 11, fontWeight: '900' },
  brandEyebrow: { color: '#9edbd5', fontSize: 11, fontWeight: '900' },
  brandTitle: {
    color: '#ffffff',
    fontSize: 42,
    lineHeight: 46,
    fontWeight: '900',
  },
  brandCopy: { color: '#d5e3f3', fontSize: 16, lineHeight: 24 },
  featureList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  featurePill: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    color: '#ffffff',
    backgroundColor: 'rgba(255,255,255,0.12)',
    fontSize: 13,
    fontWeight: '900',
  },
  accountPanel: { padding: 22, gap: 16, backgroundColor: '#ffffff' },
  accountPanelHeading: { gap: 7 },
  panelKicker: { color: '#115e59', fontSize: 12, fontWeight: '900' },
  panelTitle: {
    color: '#17202a',
    fontSize: 30,
    lineHeight: 35,
    fontWeight: '900',
  },
  accountCopy: { color: '#697586', fontSize: 15, lineHeight: 23 },
  modeSwitch: {
    padding: 4,
    flexDirection: 'row',
    gap: 4,
    borderRadius: 8,
    backgroundColor: '#eef1f5',
  },
  modeButton: {
    flex: 1,
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
  },
  activeModeButton: {
    backgroundColor: '#ffffff',
    shadowColor: '#121926',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  modeButtonText: { color: '#697586', fontWeight: '800' },
  activeModeButtonText: { color: '#115e59' },
  fieldLabel: { color: '#17202a', fontWeight: '800', marginBottom: -8 },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: '#d9dee7',
    borderRadius: 8,
    paddingHorizontal: 14,
    color: '#17202a',
    backgroundColor: '#ffffff',
    fontSize: 16,
  },
  accountMessageError: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ffd1cc',
    color: '#b42318',
    backgroundColor: '#fff1f0',
    lineHeight: 21,
  },
  accountSubmit: {
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#0f766e',
  },
  accountSubmitDisabled: { backgroundColor: '#e5e9ef' },
  accountSubmitText: { color: '#ffffff', fontWeight: '800', fontSize: 16 },
  accountSubmitDisabledText: { color: '#8b95a1' },
  chatScreen: {
    flex: 1,
    margin: 0,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
  },
  roomScreen: { flex: 1, backgroundColor: '#f8fafc' },
  drawerBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  drawerBackdropTouch: {
    flex: 1,
  },
  sideDrawer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '82%',
    maxWidth: 320,
    zIndex: 30,
    backgroundColor: '#162330',
    shadowColor: '#0f172a',
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: { width: 12, height: 0 },
    elevation: 8,
  },
  drawerProfile: {
    minHeight: 162,
    paddingHorizontal: 22,
    paddingTop: 26,
    paddingBottom: 20,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 14,
    backgroundColor: '#14202c',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148, 163, 184, 0.14)',
  },
  drawerAvatar: {
    width: 66,
    height: 66,
    borderRadius: 33,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f766e',
  },
  drawerAvatarText: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
  },
  drawerProfileText: {
    minWidth: 0,
    flex: 1,
    gap: 6,
  },
  drawerProfileName: {
    color: '#e8eef6',
    fontSize: 20,
    fontWeight: '800',
  },
  drawerProfileMeta: {
    color: '#7ab8ff',
    fontSize: 14,
    fontWeight: '700',
  },
  drawerClose: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  drawerCloseText: {
    color: '#9aa8b8',
    fontSize: 26,
    lineHeight: 26,
  },
  drawerMenu: {
    paddingVertical: 12,
  },
  drawerMenuItem: {
    minHeight: 56,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  drawerMenuIcon: {
    width: 34,
    color: '#d5e3f3',
    fontSize: 22,
    textAlign: 'center',
  },
  drawerMenuLabel: {
    color: '#e8eef6',
    fontSize: 17,
    fontWeight: '800',
  },
  roomSidebarHeader: {
    minHeight: 62,
    paddingHorizontal: 10,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#d9dee7',
    backgroundColor: '#f8fafc',
  },
  menuButton: {
    width: 34,
    height: 34,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderRadius: 8,
  },
  menuLine: {
    width: 20,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#697586',
  },
  roomHeaderText: { minWidth: 0, flex: 1 },
  roomScreenTitle: {
    color: '#17202a',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '900',
  },
  roomScreenSubtitle: {
    color: '#697586',
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  chatSubtitle: {
    maxWidth: '100%',
    marginTop: 6,
    color: '#697586',
    fontSize: 13,
    fontWeight: '700',
  },
  memberSummaryButton: {
    marginTop: 2,
  },
  drawerToolbar: {
    minHeight: 78,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#162330',
  },
  drawerBackButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  drawerBackButtonText: {
    color: '#9aa8b8',
    fontSize: 34,
    lineHeight: 34,
  },
  drawerToolbarTitle: {
    flex: 1,
    color: '#e8eef6',
    fontSize: 24,
    fontWeight: '900',
  },
  drawerSearch: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148, 163, 184, 0.14)',
    backgroundColor: '#162330',
  },
  drawerSearchInput: {
    minHeight: 42,
    paddingHorizontal: 14,
    color: '#dbe7f3',
    backgroundColor: '#243244',
    borderRadius: 999,
    fontSize: 15,
  },
  drawerContactList: {
    padding: 8,
    gap: 16,
  },
  drawerSection: {
    gap: 8,
  },
  drawerSectionTitle: {
    marginTop: 8,
    marginBottom: 2,
    color: '#7ab8ff',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  drawerEmpty: {
    margin: 12,
    color: '#93a4b7',
    fontSize: 14,
  },
  drawerContactFooter: {
    paddingBottom: 24,
  },
  drawerPrimaryAction: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#0f766e',
  },
  drawerPrimaryActionText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  sidebarSearch: { paddingHorizontal: 8, paddingTop: 10, paddingBottom: 6 },
  searchInput: {
    minHeight: 38,
    paddingHorizontal: 10,
    color: '#17202a',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d9dee7',
    borderRadius: 8,
    fontSize: 15,
  },
  roomList: { paddingHorizontal: 10, paddingBottom: 10 },
  refreshRow: {
    minHeight: 38,
    marginBottom: 4,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#eaf5f3',
  },
  refreshRowText: { color: '#115e59', fontWeight: '900' },
  emptyMenu: { margin: 12, color: '#697586', fontSize: 13 },
  roomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 8,
  },
  drawerRoomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 8,
  },
  roomItem: {
    flex: 1,
    minHeight: 72,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 8,
  },
  drawerRoomItem: {
    flex: 1,
    minHeight: 66,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 8,
  },
  roomItemWithAction: {
    paddingRight: 6,
  },
  roomItemActive: { backgroundColor: '#eaf5f3' },
  roomAvatar: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 23,
    backgroundColor: '#0f766e',
  },
  roomAvatarText: { color: '#ffffff', fontSize: 17, fontWeight: '900' },
  drawerRoomAvatar: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 23,
    backgroundColor: '#0f766e',
  },
  drawerRoomAvatarText: { color: '#ffffff', fontSize: 17, fontWeight: '900' },
  roomOnlineDot: {
    position: 'absolute',
    right: 1,
    bottom: 1,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#f8fafc',
    backgroundColor: '#16a34a',
  },
  roomContent: { minWidth: 0, flex: 1, gap: 4 },
  roomTopline: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8 },
  roomBottomline: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8 },
  roomName: { minWidth: 0, flex: 1, color: '#17202a', fontSize: 16, fontWeight: '900' },
  roomPreview: { minWidth: 0, flex: 1, color: '#697586', fontSize: 14 },
  roomTime: { color: '#697586', fontSize: 13, fontWeight: '700' },
  header: {
    minHeight: 82,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#d9dee7',
    backgroundColor: '#ffffff',
    gap: 12,
    flexWrap: 'wrap',
  },
  chatHeaderMain: {
    minWidth: 0,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  backButtonText: { color: '#697586', fontSize: 34, lineHeight: 34 },
  chatTitleBlock: { minWidth: 0, flex: 1, gap: 3 },
  headerTitle: { color: '#17202a', fontSize: 24, lineHeight: 28, fontWeight: '900' },
  headerActions: {
    width: '100%',
    paddingLeft: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    flexWrap: 'wrap',
  },
  status: {
    minWidth: 76,
    minHeight: 28,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    backgroundColor: '#eef1f5',
  },
  statusConnected: { backgroundColor: '#d9f3ee' },
  statusText: { color: '#697586', fontSize: 12, fontWeight: '900' },
  statusConnectedText: { color: '#0f766e' },
  headerButton: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#d9dee7',
  },
  headerButtonText: { color: '#17202a', fontWeight: '800' },
  headerButtonDanger: {
    backgroundColor: '#fff1f0',
    borderColor: '#ffd1cc',
  },
  headerButtonDangerText: {
    color: '#b42318',
  },
  connectionError: {
    padding: 12,
    borderWidth: 1,
    borderColor: '#ffd1cc',
    backgroundColor: '#fff1f0',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    gap: 12,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderRadius: 0,
  },
  connectionErrorText: {
    color: '#b42318',
    fontSize: 14,
    lineHeight: 20,
  },
  connectionErrorButton: {
    minHeight: 34,
    width: '100%',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#b42318',
  },
  connectionErrorButtonText: {
    color: '#ffffff',
    fontWeight: '800',
  },
  notice: {
    marginHorizontal: 16,
    marginTop: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#cfe6ff',
    backgroundColor: '#edf6ff',
  },
  noticeText: { color: '#41546d' },
  messageDateDivider: {
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
    backgroundColor: 'rgba(51, 65, 85, 0.72)',
  },
  badge: {
    minWidth: 22,
    height: 22,
    paddingHorizontal: 7,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f766e',
  },
  badgeText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  messageList: {
    flexGrow: 1,
    padding: 16,
    paddingBottom: 18,
    backgroundColor: '#f7f9fb',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingTop: 80,
  },
  emptyText: {
    maxWidth: 320,
    color: '#697586',
    textAlign: 'center',
    lineHeight: 24,
  },
  stockEmptyState: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 460,
    marginTop: 40,
    padding: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: '#d9dee7',
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  stockEmptyKicker: {
    color: '#0f766e',
    fontSize: 12,
    fontWeight: '900',
  },
  stockEmptyTitle: {
    color: '#17202a',
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
  },
  stockEmptyText: {
    color: '#697586',
    fontSize: 15,
    lineHeight: 22,
  },
  stockQuickActions: {
    marginTop: 2,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stockQuickAction: {
    width: '48%',
    minHeight: 42,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b9ded8',
    backgroundColor: '#e7f5f2',
  },
  stockQuickActionText: {
    color: '#115e59',
    fontWeight: '800',
  },
  stockEmptyHint: {
    color: '#8b95a1',
    fontSize: 12,
  },
  imagePreviewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  imagePreviewContent: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePreviewClose: {
    position: 'absolute',
    top: -4,
    right: 0,
    zIndex: 2,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  imagePreviewCloseText: {
    color: '#ffffff',
    fontSize: 30,
    lineHeight: 30,
  },
  imagePreviewFull: {
    width: '100%',
    height: '82%',
    borderRadius: 8,
    resizeMode: 'contain',
  },
  messageRow: { position: 'relative', alignItems: 'flex-start', marginBottom: 10 },
  selfMessageRow: { alignItems: 'flex-end' },
  messageTail: {
    position: 'absolute',
    bottom: 8,
    width: 16,
    height: 10,
    borderBottomWidth: 1,
  },
  otherMessageTail: {
    left: -4,
    backgroundColor: '#ffffff',
    borderBottomColor: '#dbe2ea',
    borderBottomLeftRadius: 8,
    transform: [{ rotate: '-18deg' }],
  },
  selfMessageTail: {
    right: -4,
    backgroundColor: '#2f5f8d',
    borderBottomColor: '#2f5f8d',
    borderBottomRightRadius: 8,
    transform: [{ rotate: '18deg' }],
  },
  messageBubble: {
    maxWidth: '88%',
    paddingHorizontal: 12,
    paddingTop: 9,
    paddingBottom: 7,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dbe2ea',
  },
  selfMessageBubble: { backgroundColor: '#2f5f8d', borderColor: '#2f5f8d' },
  senderText: { color: '#697586', fontSize: 12, fontWeight: '700', marginBottom: 3 },
  messageText: { color: '#17202a', fontSize: 16, lineHeight: 22 },
  selfMessageText: { color: '#ffffff' },
  typingIndicator: {
    minWidth: 52,
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#8aa0b7',
  },
  stockCard: {
    minWidth: 240,
    gap: 10,
  },
  stockCardHeader: {
    gap: 2,
  },
  stockCardKicker: {
    color: '#697586',
    fontSize: 11,
    fontWeight: '900',
  },
  stockCardSymbol: {
    color: '#17202a',
    fontSize: 22,
    fontWeight: '900',
  },
  stockCardMetrics: {
    flexDirection: 'row',
    gap: 10,
  },
  stockCardMetric: {
    flex: 1,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#ffffff',
  },
  stockCardMetricLabel: {
    color: '#697586',
    fontSize: 12,
    marginBottom: 4,
  },
  stockCardMetricValue: {
    color: '#17202a',
    fontSize: 18,
    fontWeight: '900',
  },
  stockCardValueUp: {
    color: '#b42318',
  },
  stockCardValueDown: {
    color: '#0f766e',
  },
  stockCardDividend: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    gap: 8,
  },
  stockCardEmpty: {
    color: '#697586',
    fontSize: 13,
  },
  stockCardSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  stockCardSummaryLabel: {
    flex: 1,
    color: '#697586',
    fontSize: 12,
  },
  stockCardSummaryValue: {
    flex: 1,
    color: '#17202a',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  stockCardRecords: {
    gap: 6,
  },
  stockCardRecordRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  stockCardRecordDate: {
    color: '#697586',
    fontSize: 12,
  },
  stockCardRecordAmount: {
    color: '#17202a',
    fontSize: 12,
    fontWeight: '800',
  },
  messageAttachment: {
    marginTop: 8,
    overflow: 'hidden',
    borderRadius: 8,
  },
  messageAttachmentImage: {
    width: 260,
    height: 260,
    borderRadius: 8,
    backgroundColor: '#d9dee7',
  },
  messageAttachmentFile: {
    minWidth: 180,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  messageAttachmentFileLabel: {
    color: '#697586',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 3,
  },
  messageAttachmentFileName: {
    color: '#17202a',
    fontSize: 14,
    fontWeight: '800',
  },
  messageAttachmentFileMeta: {
    color: '#697586',
    fontSize: 12,
    marginTop: 3,
  },
  messageAttachmentActionText: {
    color: '#115e59',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 6,
  },
  messageFooter: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  timeText: {
    color: '#697586',
    fontSize: 11,
  },
  selfTimeText: { color: 'rgba(219, 234, 254, 0.76)' },
  readReceiptText: {
    color: '#697586',
    fontSize: 11,
    fontWeight: '700',
  },
  readReceiptTextRead: {
    color: '#67d7ff',
  },
  composerShell: {
    borderTopWidth: 1,
    borderTopColor: '#d9dee7',
    backgroundColor: '#ffffff',
  },
  composerInputStack: {
    minWidth: 0,
    flex: 1,
    gap: 8,
  },
  attachmentPreview: {
    minHeight: 64,
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#d9dee7',
    borderRadius: 8,
    backgroundColor: '#f6f8fb',
  },
  attachmentPreviewImage: {
    width: 48,
    height: 48,
    borderRadius: 6,
    backgroundColor: '#d9dee7',
  },
  attachmentPreviewIcon: {
    width: 48,
    height: 48,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d9dee7',
  },
  attachmentPreviewIconText: {
    color: '#115e59',
    fontSize: 18,
    fontWeight: '900',
  },
  attachmentPreviewBody: {
    minWidth: 0,
    flex: 1,
    gap: 4,
  },
  attachmentPreviewName: {
    color: '#17202a',
    fontSize: 13,
    fontWeight: '800',
  },
  attachmentPreviewMeta: {
    color: '#697586',
    fontSize: 12,
    fontWeight: '700',
  },
  attachmentRemoveButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d9dee7',
  },
  attachmentRemoveButtonText: {
    color: '#697586',
    fontSize: 24,
    lineHeight: 24,
  },
  composerStatus: {
    color: '#697586',
    fontSize: 12,
    fontWeight: '700',
  },
  composer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: '#ffffff',
  },
  attachButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(15, 118, 110, 0.28)',
    backgroundColor: '#d9f3ee',
  },
  attachButtonHidden: { display: 'none' },
  attachButtonText: {
    color: '#115e59',
    fontSize: 24,
    lineHeight: 24,
  },
  composerInput: {
    minHeight: 44,
    maxHeight: 110,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d9dee7',
    backgroundColor: '#ffffff',
    color: '#17202a',
    fontSize: 16,
  },
  sendButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#0f766e',
    flexDirection: 'row',
    gap: 6,
  },
  sendButtonStock: {
    width: 'auto',
    minWidth: 82,
    paddingHorizontal: 16,
    backgroundColor: '#17202a',
  },
  disabledSendButton: { opacity: 0.45 },
  sendButtonIcon: { color: '#ffffff', fontSize: 20, lineHeight: 20, fontWeight: '900' },
  sendButtonText: { color: '#ffffff', fontSize: 14, fontWeight: '800' },
  roomActionButton: {
    minWidth: 54,
    minHeight: 34,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d9dee7',
    backgroundColor: '#f8fafc',
  },
  roomActionButtonFilled: {
    minWidth: 54,
    minHeight: 34,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#0f766e',
  },
  roomActionButtonText: {
    color: '#17202a',
    fontSize: 13,
    fontWeight: '800',
  },
  roomActionButtonFilledText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  roomActionButtonDanger: {
    borderColor: '#ffd1cc',
    backgroundColor: '#fff1f0',
  },
  roomActionButtonDangerText: {
    color: '#b42318',
  },
  friendRequestCard: {
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#1d2b39',
    gap: 10,
  },
  friendRequestText: {
    gap: 4,
  },
  friendRequestName: {
    color: '#e8eef6',
    fontSize: 15,
    fontWeight: '800',
  },
  friendRequestMeta: {
    color: '#93a4b7',
    fontSize: 13,
  },
  friendRequestActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  friendRequestGhostButton: {
    minHeight: 34,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#41546d',
  },
  friendRequestGhostButtonText: {
    color: '#d5e3f3',
    fontWeight: '800',
  },
  friendRequestPrimaryButton: {
    minHeight: 34,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#0f766e',
  },
  friendRequestPrimaryButtonText: {
    color: '#ffffff',
    fontWeight: '800',
  },
  modalBackdrop: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.36)',
  },
  sheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.36)',
  },
  sheetCard: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 28,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: '#ffffff',
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#d9dee7',
    marginBottom: 12,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sheetTitle: {
    color: '#17202a',
    fontSize: 22,
    fontWeight: '900',
  },
  sheetSubtitle: {
    color: '#697586',
    fontSize: 14,
    marginTop: 2,
    marginBottom: 14,
  },
  memberSheetList: {
    gap: 10,
  },
  memberSheetRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 4,
  },
  memberSheetAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f766e',
  },
  memberSheetAvatarText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  memberSheetName: {
    color: '#17202a',
    fontSize: 15,
    fontWeight: '800',
  },
  modalCard: {
    padding: 18,
    gap: 14,
    borderRadius: 8,
    backgroundColor: '#ffffff',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalTitle: {
    color: '#17202a',
    fontSize: 22,
    fontWeight: '900',
  },
  modalCopy: {
    color: '#697586',
    fontSize: 14,
    lineHeight: 20,
  },
  modalCloseButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  modalCloseButtonText: {
    color: '#697586',
    fontSize: 26,
    lineHeight: 26,
  },
  groupPicker: {
    maxHeight: 260,
  },
  groupPickerRow: {
    minHeight: 60,
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 8,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#d9dee7',
  },
  groupPickerRowSelected: {
    borderColor: '#0f766e',
    backgroundColor: '#eaf5f3',
  },
  groupPickerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f766e',
  },
  groupPickerAvatarText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  groupPickerBody: {
    minWidth: 0,
    flex: 1,
    gap: 2,
  },
  groupPickerName: {
    color: '#17202a',
    fontSize: 15,
    fontWeight: '800',
  },
  groupPickerMeta: {
    color: '#697586',
    fontSize: 13,
  },
  groupPickerCheck: {
    width: 24,
    textAlign: 'center',
    color: '#115e59',
    fontSize: 20,
    fontWeight: '900',
  },
})
